# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f7fc50728ccc6310e314a79cffffaf21becc4569a58e3e410d98c40b6ede8c93437f45673efdc8c61074891cd7bfdd0b8f7e4313b49603996a71204554644c8

test:
  secret_key_base: e28163557bb05708a44517f7f9cc105be51ebd18bc06c72436f7cfef0ff431e00015f93dbef6db7662230169fd3c8272003f252dc7dd67c63a894d8a005db2cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
